use sales;

-- 1. Calculate the number of orders per month in 2018.
select count(order_id) as toatl_order_in_2018 from orders where YEAR(order_purchase_timestamp) = 2018;

select MONTH(order_purchase_timestamp) as Month, count(*) as Total_Order 
from orders
where year(order_purchase_timestamp) = 2018
group by MONTH(order_purchase_timestamp) order by Month asc;



--2. Find the average number of products per order, grouped by customer city.
with count_per_order as 
(select orders.order_id, orders.customer_id, count(order_items.order_id) as oc
from orders join order_items
on orders.order_id = order_items.order_id
group by orders.order_id, orders.customer_id)

select customers.customer_city, round(avg(count_per_order.oc),2) average_orders
from customers join count_per_order
on customers.customer_id = count_per_order.customer_id
group by customers.customer_city order by average_orders desc;





-- 3. Calculate the percentage of total revenue contributed by each product category.
SELECT p.product_category, round(sum(oi.price)/ (select sum(price) from order_items)* 100,2) as revenue_parcentage 
from order_items as oi 
join products p on oi.product_id= p.product_id
group by p.product_category order by revenue_parcentage desc;




--4. Identify the correlation between product price and the number of times a product has been purchased.
SELECT p.product_category,
AVG(oi.price) AS avg_price,
COUNT(oi.order_id) AS times_purchased
FROM products AS p
JOIN order_items AS oi ON p.product_id = oi.product_id
GROUP BY p.product_category ORDER BY times_purchased DESC;





--5. Calculate the total revenue generated by each seller, and rank them by revenue.
SELECT seller_id,
       SUM(price) AS total_revenue
FROM order_items
GROUP BY seller_id
ORDER BY total_revenue DESC;