create database customer_behavior;


use customer_behavior;
select * from customer;


--Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount_USD) as revenue
from customer group by gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount_USD from customer 
where discount_applied= 'YES' and purchase_amount_USD >= (select avg(purchase_amount_USD) from customer)

-- Q3. Which are the top 5 products with the highest average review rating?
select top 5 item_purchased, round(avg(review_rating),2) as Average_Product_Rating from customer
group by item_purchased order by Average_Product_Rating desc;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, 
ROUND(AVG(purchase_amount_USD),2)
from customer where shipping_type in ('Standard','Express')
group by shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount_USD),2) AS avg_spend,
       ROUND(SUM(purchase_amount_USD),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select top 5 item_purchased, round(100 * sum(case when discount_applied= 'yes' then 1 else 0 end)/ count(*), 2) as discount_rate
from customer group by Item_Purchased order by discount_rate desc;

--Q7. Segment customers into New, Returning, and Loyal based on their total  number of previous purchases, and show the count of each segment. 
-- Alter table customer alter column previous_purchases int; conver the previous_perchases column nvarchar to int

with customer_type as ( select customer_id, previous_purchases,
case when previous_purchases = 1 then 'new'
when previous_purchases between 2 and 10 then 'returning'
else 'loyal' end as customer_segment from customer)

select customer_segment, count(*) as Number_of_customers from customer_type group by customer_segment;

--Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
SELECT category,item_purchased, COUNT(customer_id) AS total_orders,
ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank FROM customer GROUP BY category, item_purchased)

SELECT item_rank,category, item_purchased, total_orders FROM item_counts WHERE item_rank <=3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status, count(customer_id) as Repeat_buyers from customer 
where Previous_Purchases > 5 group by Subscription_Status;

--Q10. What is the revenue contribution of each age group? 
SELECT age, SUM(Purchase_Amount_USD) AS total_revenue
FROM customer
GROUP BY age ORDER BY total_revenue desc;